### ISSUE TITLE
TFE example does not work - fashion mnist dataset does not work

### ISSUE THREAD

**Issue by theRealSuperMario** [pesser/edflow#141]
**Describe the bug**

  File "/home/xxx/Projekte/gitlab_projects/2019_ma_hd/ma_code/edflow_stable/edflow/datasets/fashionmnist.py", line 73, in _load
    self._length = self._labels.shape[0]
AttributeError: 'dict' object has no attribute 'shape'

**To Reproduce**
edflow -t template_tfe/config.yaml -n hello_tfe

The problem can be blamed to https://github.com/pesser/edflow/blob/e3816e1160c9733ff4828b29de1ab73cb5d85738/edflow/data/dataset.py#L310

and was Introduced in cb5e8dd .

The fashion mnist data loader then sets `self.labels` with `self._labels`.
This then overwrites `self._labels` because the setter is overloaded.

https://github.com/pesser/edflow/blob/e3816e1160c9733ff4828b29de1ab73cb5d85738/edflow/datasets/fashionmnist.py#L70

**Comment by pesser** [comment]
should have been fixed by #140
